services:
  app:
    image: gradle:8.10.2-jdk17
    working_dir: /app
    command: ["gradle", "bootRun", "--no-daemon", "--continuous"]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - GRADLE_OPTS=-Dorg.gradle.daemon=false
      - JAVA_TOOL_OPTIONS=-Duser.timezone=UTC
      - INTERNAL_API_KEY=internal-api-key

      # Authentication
      - AUTH_SERVICE_ENDPOINT=http://mock-auth:3000
      - AUTH_SERVICE_API_KEY=test-api-key

      # Database
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=sight
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test

      # Discord feature flag
      - DISCORD_ENABLED=false
    env_file:
      - ".env"
    stdin_open: true
    tty: true
    depends_on:
      - mock-auth
      - mysql

  mock-auth:
    image: mockoon/cli:9.3.0
    ports:
      - "3000:3000"
    volumes:
      - ./mock:/data
    command:
      ["--data", "/data/mockoon-config.json", "--watch", "--port", "3000"]

  mysql:
    image: mysql:8.0.43
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=sight
      - TZ=Asia/Seoul
    volumes:
      - ./.mysql:/docker-entrypoint-initdb.d

volumes:
  gradle-cache:
